Add header overrides to download function
talkiq/gcloud-aio pull request #200
Opened 2020-08-29 04:36 UTC by domZippilli

Addresses #195 and other cases (toggling gzip transcoding, for example) by allowing the caller to supply a dictionary of headers. These headers are applied over the default session headers.

With this update, users can download ranges as follows:

```
await client.download(bucket,
                      blob,
                      headers={"Range": f"bytes={start}-{end}"})
```

2020-09-09 00:08 UTC, TheKevJames requested changes
Thanks for the contribution! Overall, this looks good -- it'll be great to allow for custom header usage here :)

2020-09-09 00:08 UTC, TheKevJames commented on storage/gcloud/aio/storage/storage.py
> +                       headers: dict = {},
Please have the default here be `None`. Using a mutable object as a default value can lead to some [unexpected behaviour in Python](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) and should generally be avoided.

2020-12-09 02:26 UTC, TheKevJames commented
Fixed up and merged as 640a2dd3448294bb3ab5801f5328e7c2e7a64854. Will be included in `gcloud-*-storage==5.7.0`

2020-12-09 02:26 UTC, closed without merging

2020-12-09 07:27 UTC, domZippilli commented
Thank you @TheKevJames! Shortly after making this PR, we had a baby that arrived a bit early and I've been on leave a while... I lost this in the inbox deluge while I was away.

2020-12-09 23:12 UTC, TheKevJames commented
No problem at all -- and congratulations!