chore(pubsub): add backoff to pull
talkiq/gcloud-aio pull request #338
Opened 2021-05-05 19:32 UTC by shaundialpad

Adds backoff directly to the pull method of the `SubscriberClient` (done here to be consistent with other parts of `gcloud-aio`,  e.g. https://github.com/talkiq/gcloud-aio/blob/e410a9cbaa3304634ce1283195ea9b8b725c5e46/auth/gcloud/aio/auth/token.py#L208

Also used the generic `Exception` solely for consistency.

Currently, a single failed `pull` request (e.g. 502 or other transient errors) will shut down the subscriber. Let's give it a chance to succeed.

2021-05-05 19:52 UTC, amartsinovich-dialpad requested changes
I believe exponential backoff can grow up to `2 ** 5 = 32s`? That might affect performance quite a bit if a consumer  goes to sleep for half a minute with k8s controller not knowing something is wrong. Let's maybe use a faster strategy?

2021-05-05 20:05 UTC, shaundialpad commented
> I believe exponential backoff can grow up to `2 ** 5 = 32s`? That might affect performance quite a bit if a consumer goes to sleep for half a minute with k8s controller not knowing something is wrong. Let's maybe use a faster strategy?

Hmm It seems to be doing what we want. Do you have any suggestions? Maybe simply enforcing `max_time` to 10 seconds or so?

2021-05-05 20:15 UTC, amartsinovich-dialpad commented
@shaundialpad How about `constant` wait strategy? This way we can retry 5 times in 5 seconds + response latency. We don't particularly care about putting too much stress on google servers, so expo backoff won't do much, only increase time to recovery.

2021-05-05 23:35 UTC, TheKevJames requested changes
I don't think this is the right place for this:

We have the backoff handling in the gcloud-aio-auth lib explicitly because Google has a line in its docs mentioning that all calls to that endpoint need to have the specified backoff policy.

In this case, though, the exact policy is incredibly dependent on the use-case, as evidenced by your discussion in PR. We can not and should not define a single strategy which all possible consumers of this library agree with; instead, this should be up to the application to specify. Instead, applications who want to implement backoff should re-wrap this method with their preferred arguments.

Even in our own systems I'm sure we'd have multiple different values we'd want (eg. realtime vs postcall process is almost certainly going to want to tradeoff speed for resilience!).

2021-05-06 17:54 UTC, shaundialpad commented
> We have the backoff handling in the gcloud-aio-auth lib explicitly because Google has a line in its docs mentioning that all calls to that endpoint need to have the specified backoff policy.

Good to know. On a related note, maybe we should have that commented?

> In this case, though, the exact policy is incredibly dependent on the use-case, as evidenced by your discussion in PR. We can not and should not define a single strategy which all possible consumers of this library agree with; instead, this should be up to the application to specify. Instead, applications who want to implement backoff should re-wrap this method with their preferred arguments.

Mmm yes I agree. Actually, the fact that the user passes in `SubscriberClient` did not occur to me. So would the expected approach that one should take look something like

```
class SubscriberClientWithBackoff(SubscriberClient):

    @backoff.on_exception(backoff.expo, Exception, max_time=10)
    async def pull(self, *args, **kwargs):
        return await super().pull(*args, **kwargs)
```

?

2021-05-06 19:00 UTC, TheKevJames commented
> Good to know. On a related note, maybe we should have that commented?

Yeah, good call. I'll dig up the relevant doc and toss it into a comment :+1:

> `SubscriberClientWithBackoff`

Yeah, that makes a lot of sense to me as you have it! I suppose this is another thing worth documenting to help out future folks who hit this.

> And as a followup, is complete shutdown of `subscribe` after a single failed pull as default behavior the correct approach?

That's harder to say. This sounds like another case where I think users would need to configure it -- I could imagine use-cases for failingfast or for retrying up to some timeout or...

2021-05-06 19:43 UTC, shaundialpad commented
Closing in favour of having the user implement their own handling and configuration.

2021-05-06 19:43 UTC, closed without merging